import { Category, Product, Review, Testimonial, Resource } from '@/types'

export const categories: Category[] = [
  { _id: '1', name: 'CRM Software', slug: 'crm', description: 'Customer relationship management tools to manage interactions with customers and prospects.', icon: '/images/crm.svg', productCount: 850, subcategories: [{ name: 'Small Business CRM', slug: 'small-business-crm' }, { name: 'Enterprise CRM', slug: 'enterprise-crm' }, { name: 'Real Estate CRM', slug: 'real-estate-crm' }] },
  { _id: '2', name: 'HR Software', slug: 'hr', description: 'Human resources software for managing employee data, payroll, benefits and more.', icon: '/images/hr.svg', productCount: 620, subcategories: [{ name: 'Payroll Software', slug: 'payroll' }, { name: 'Benefits Administration', slug: 'benefits-administration' }, { name: 'Applicant Tracking', slug: 'applicant-tracking' }] },
  { _id: '3', name: 'EMR Software', slug: 'emr-software', description: 'Electronic medical records software for healthcare practices and hospitals.', icon: '/images/emr.svg', productCount: 480, subcategories: [{ name: 'Cloud EMR', slug: 'cloud-emr' }, { name: 'Mental Health EHR', slug: 'mental-health-ehr' }, { name: 'Dental EHR', slug: 'dental-ehr' }] },
  { _id: '4', name: 'LMS Software', slug: 'lms', description: 'Learning management systems for training, education, and skill development.', icon: '/images/lms.svg', productCount: 350, subcategories: [{ name: 'Corporate LMS', slug: 'corporate-lms' }, { name: 'Academic LMS', slug: 'academic-lms' }, { name: 'Compliance Training', slug: 'compliance-training' }] },
  { _id: '5', name: 'Project Management', slug: 'project-management', description: 'Tools for planning, organizing, and managing project resources and timelines.', icon: '/images/pm.svg', productCount: 420, subcategories: [{ name: 'Agile Tools', slug: 'agile-tools' }, { name: 'Gantt Chart Software', slug: 'gantt-chart' }, { name: 'Kanban Boards', slug: 'kanban-boards' }] },
  { _id: '6', name: 'Accounting Software', slug: 'accounting-software', description: 'Financial management tools for bookkeeping, invoicing, and expense tracking.', icon: '/images/accounting.svg', productCount: 390, subcategories: [{ name: 'Small Business Accounting', slug: 'small-business-accounting' }, { name: 'Enterprise Accounting', slug: 'enterprise-accounting' }, { name: 'Tax Software', slug: 'tax-software' }] },
  { _id: '7', name: 'Marketing Software', slug: 'marketing', description: 'Digital marketing platforms for email, social media, SEO, and campaign management.', icon: '/images/marketing.svg', productCount: 510, subcategories: [{ name: 'Email Marketing', slug: 'email-marketing' }, { name: 'Social Media Management', slug: 'social-media-management' }, { name: 'SEO Tools', slug: 'seo-tools' }] },
  { _id: '8', name: 'Customer Service', slug: 'customer-service', description: 'Help desk and support software to manage customer inquiries and tickets.', icon: '/images/cs.svg', productCount: 280, subcategories: [{ name: 'Help Desk', slug: 'help-desk' }, { name: 'Live Chat', slug: 'live-chat' }, { name: 'Knowledge Base', slug: 'knowledge-base' }] },
]

export const products: Product[] = [
  { _id: 'p1', name: 'SalesFlow', slug: 'salesflow', tagline: 'Modern CRM for growing sales teams', description: 'SalesFlow helps you track leads, manage pipelines, and close deals faster with AI-powered insights.', logo: '', website: 'https://salesflow.example.com', category: categories[0], pricing: 'From $29/user/mo', rating: 4.5, reviewCount: 234, features: ['Pipeline Management', 'Email Tracking', 'AI Lead Scoring', 'Reporting Dashboards'] },
  { _id: 'p2', name: 'PeopleFirst HR', slug: 'peoplefirst-hr', tagline: 'All-in-one HR platform for modern workplaces', description: 'Manage payroll, benefits, time-off, and performance reviews in one place.', logo: '', website: 'https://peoplefirst.example.com', category: categories[1], pricing: 'From $8/employee/mo', rating: 4.3, reviewCount: 187, features: ['Payroll Processing', 'Benefits Admin', 'Time Tracking', 'Performance Reviews'] },
  { _id: 'p3', name: 'MediRecord EMR', slug: 'medirecord-emr', tagline: 'Cloud-based EMR for small to mid-size practices', description: 'Streamline clinical workflows with customizable templates, e-prescribing, and patient portal.', logo: '', website: 'https://medirecord.example.com', category: categories[2], pricing: 'From $299/provider/mo', rating: 4.1, reviewCount: 156, features: ['Custom Templates', 'e-Prescribing', 'Patient Portal', 'Billing Integration'] },
  { _id: 'p4', name: 'LearnPath LMS', slug: 'learnpath-lms', tagline: 'Engaging learning platform for teams', description: 'Create, deliver, and track training programs with an intuitive LMS built for engagement.', logo: '', website: 'https://learnpath.example.com', category: categories[3], pricing: 'From $5/user/mo', rating: 4.6, reviewCount: 203, features: ['Course Authoring', 'Assessments', 'Gamification', 'Analytics'] },
  { _id: 'p5', name: 'TaskForge', slug: 'taskforge', tagline: 'Project management that teams love', description: 'Kanban boards, Gantt charts, and time tracking in a single collaborative workspace.', logo: '', website: 'https://taskforge.example.com', category: categories[4], pricing: 'From $12/user/mo', rating: 4.4, reviewCount: 312, features: ['Kanban Boards', 'Gantt Charts', 'Time Tracking', 'Team Collaboration'] },
  { _id: 'p6', name: 'BooksBalance', slug: 'booksbalance', tagline: 'Smart accounting for small businesses', description: 'Invoicing, expense tracking, bank reconciliation, and financial reports made simple.', logo: '', website: 'https://booksbalance.example.com', category: categories[5], pricing: 'From $15/mo', rating: 4.2, reviewCount: 178, features: ['Invoicing', 'Expense Tracking', 'Bank Reconciliation', 'Financial Reports'] },
  { _id: 'p7', name: 'MailCraft', slug: 'mailcraft', tagline: 'Email marketing that drives results', description: 'Design beautiful emails, automate campaigns, and measure performance with detailed analytics.', logo: '', website: 'https://mailcraft.example.com', category: categories[6], pricing: 'From $19/mo', rating: 4.0, reviewCount: 145, features: ['Email Designer', 'Automation', 'A/B Testing', 'Analytics'] },
  { _id: 'p8', name: 'SupportHub', slug: 'supporthub', tagline: 'Customer support platform for teams of all sizes', description: 'Ticketing, live chat, and knowledge base in one unified platform.', logo: '', website: 'https://supporthub.example.com', category: categories[7], pricing: 'From $49/agent/mo', rating: 4.3, reviewCount: 198, features: ['Ticketing System', 'Live Chat', 'Knowledge Base', 'Multi-channel'] },
]

export const reviews: Review[] = [
  { _id: 'r1', product: 'SalesFlow', user: 'Sarah M.', rating: 5, title: 'Transformed our sales process', body: 'SalesFlow helped us increase our close rate by 40%. The pipeline management is intuitive and the AI lead scoring is remarkably accurate.', pros: 'Easy to use, great AI features, excellent support', cons: 'Mobile app could be improved', createdAt: '2026-06-15' },
  { _id: 'r2', product: 'SalesFlow', user: 'James R.', rating: 4, title: 'Solid CRM with room to grow', body: 'Good product overall. The reporting is powerful once you get used to it. Integration with our existing tools was seamless.', pros: 'Great integrations, powerful reporting', cons: 'Steep learning curve for advanced features', createdAt: '2026-05-20' },
  { _id: 'r3', product: 'PeopleFirst HR', user: 'Lisa K.', rating: 5, title: 'Best HR tool we have used', body: 'PeopleFirst simplified our entire HR process. Payroll runs smoothly and the benefits administration is a breeze.', pros: 'All-in-one platform, great UX', cons: 'None really', createdAt: '2026-07-01' },
  { _id: 'r4', product: 'LearnPath LMS', user: 'David W.', rating: 5, title: 'Engaging and easy to use', body: 'Our employees actually enjoy using LearnPath. The gamification features boosted course completion rates significantly.', pros: 'Engaging, great analytics, easy course creation', cons: 'Wish there were more template options', createdAt: '2026-06-28' },
  { _id: 'r5', product: 'TaskForge', user: 'Emily T.', rating: 4, title: 'Great for team collaboration', body: 'TaskForge replaced three different tools for us. The kanban boards and time tracking integration is fantastic.', pros: 'All-in-one, clean UI, fast', cons: 'Reporting could be more customizable', createdAt: '2026-06-10' },
]

export const testimonials: Testimonial[] = [
  { name: 'Rachael Ashley', company: 'Studio Dwell', role: 'Owner', avatar: '', quote: 'I stumbled upon Zanwik when I was looking for software for my small business. I was amazed at how easy it was to navigate through the site, and the user reviews were a great help in making an informed decision.', stats: [{ label: 'Research Hours Saved', value: '6+' }, { label: 'Demo Views', value: '3+' }, { label: 'Reduce Purchase Timeline', value: '55%' }, { label: 'Narrowed Options', value: '20 to 3' }] },
  { name: 'Marcus Chen', company: 'TechFlow Inc.', role: 'CTO', avatar: '', quote: 'Zanwik saved us weeks of research. The comparison tools and honest reviews helped us choose the right enterprise software without the usual sales pressure.', stats: [{ label: 'Research Hours Saved', value: '40+' }, { label: 'Vendors Evaluated', value: '12' }, { label: 'Cost Savings', value: '30%' }] },
]

export const resources: Resource[] = [
  { _id: 'res1', title: 'AI Software Search Trends in 2026', slug: 'ai-software-trends-2026', excerpt: 'The era of "AI-lite" is over. Buyers now expect solutions that deliver measurable outcomes.', image: '', author: 'Zanwik Team', date: '2026-07-15', category: 'Trends' },
  { _id: 'res2', title: '2026 HR Tech Buyer Report', slug: '2026-hr-tech-buyer-report', excerpt: 'SaaS buyer engagement in 2026 is shifting toward personalized and trust-driven interactions.', image: '', author: 'Zanwik Team', date: '2026-06-20', category: 'Reports' },
  { _id: 'res3', title: 'From Clicks to Conversions in B2B SaaS', slug: 'clicks-to-conversions-b2b-saas', excerpt: 'Learn how top B2B SaaS companies are turning website visitors into qualified leads.', image: '', author: 'Zanwik Team', date: '2026-06-05', category: 'Guides' },
  { _id: 'res4', title: 'How Much Does an EMR Cost? (2026)', slug: 'emr-cost-2026', excerpt: 'A comprehensive breakdown of EMR pricing models and what to expect for your practice.', image: '', author: 'Zanwik Team', date: '2026-05-28', category: 'Pricing' },
]
